import { Asset } from 'expo-asset'
import type { ImageGenerationInfo } from '@superone/shared/agent-types'
import type { FilePreviewState } from '../file-preview-state'

const CODE = `import { useMemo } from 'react'
import { FileChipShell } from './presenters/FileChipShell'

/**
 * File name chip that hands the path to the native host instead of opening a
 * desktop tab. Only the tap target differs between the two surfaces.
 */
export function PortableFileChip({ name, filePath }: { name: string; filePath: string }) {
  const icon = useMemo(() => filePath.split(/[/\\\\]/).pop() || name, [filePath, name])
  return (
    <FileChipShell
      icon={icon}
      name={name}
      title={filePath}
      onClick={(event) => { event.stopPropagation(); requestNative('previewFile', { path: filePath }) }}
    />
  )
}

const VERY_LONG_LINE = 'const configuration = { retries: 3, backoffMs: [250, 500, 1000, 2000, 4000], endpoints: ["https://relay.example.com/v1", "https://relay-fallback.example.com/v1"], headers: { "x-client": "superone-mobile" } }'
`

const MARKDOWN = `# Remote file preview

A chip in the transcript opens the file **in place**, the way the desktop opens a tab.

## What arrives inline

- Text and code under 512 KiB
- Markdown, rendered as prose
- The cited line, when the chip carried one

\`\`\`ts
const inline = size <= INLINE_PREVIEW_MAX_BYTES
\`\`\`

> Anything else becomes a transfer card. Over the relay a file larger than 512 KiB needs confirmation first.
`

/** A 2×2 PNG so the fixtures need no asset pipeline. */
export const TINY_PNG = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAFElEQVR42mNk+M9Qz8DAwMDAwAAAFQ4C/1K5pFcAAAAASUVORK5CYII='

/** What a `media_generate_image` call reports — provider params, timing, a revised prompt. */
export const TOOL_GENERATION: ImageGenerationInfo = {
  revisedPrompt: 'A lone astronaut kneeling on the lunar surface, tending a glowing bonsai inside a glass geodesic dome, Earth rising over the horizon, cinematic lighting.',
  generationMs: 14_320,
  params: [
    { key: 'provider', value: 'openai' },
    { key: 'model', value: 'gpt-image-1' },
    { key: 'size', value: '1024x1536' },
  ],
  referenceImagePaths: ['/Users/me/proj/refs/bonsai.jpg'],
  warnings: ['The provider rewrote the prompt to comply with its content policy.'],
}

/** What Codex's built-in ImageGen reports — just the revised prompt and how long it took. */
export const CODEX_GENERATION: ImageGenerationInfo = {
  revisedPrompt: '9:16 portrait of an astronaut watering a luminous bonsai on the Moon; no text, logos or borders.',
  generationMs: 71_800,
}

/**
 * A three-second test pattern bundled with the app, so the video body plays
 * offline. Metro serves it over HTTP in development and from the bundle in a
 * release build; the player takes either.
 */
const SAMPLE_CLIP_URI = Asset.fromModule(require('../../assets/preview/sample-clip.mp4')).uri

const PATH = '/workspace/super-one/packages/chat-view/src/PortableToolRow.tsx'
const HERO = { path: '/workspace/super-one/art/hero.png', name: 'hero.png', size: 4_820_113, mimeType: 'image/png' }

/** Every state the preview can reach, keyed by the label the gallery shows. */
export const FILE_PREVIEW_FIXTURES: ReadonlyArray<{ label: string; state: FilePreviewState }> = [
  { label: 'Image · tool screenshot', state: { kind: 'image', path: '/Users/me/shots/screen.png', name: 'screen.png', label: 'Screenshot', src: TINY_PNG, mimeType: 'image/png' } },
  { label: 'Image · attachment, no path', state: { kind: 'image', name: 'photo.png', label: 'photo.png', src: TINY_PNG, mimeType: 'image/png' } },
  { label: 'Image · downloaded file', state: { kind: 'image', ...HERO, src: 'file:///cache/file-preview/hero.png' } },
  { label: 'Image · remote URL (nothing to save)', state: { kind: 'image', name: 'image.jpg', src: 'https://picsum.photos/seed/superone/1200/800', mimeType: 'image/jpeg' } },
  // Rotation is not symmetric: a portrait picture has to shrink to lie down,
  // and the landscape one above has to grow to stand up. Both need reviewing.
  { label: 'Image · tall portrait (turn it)', state: { kind: 'image', name: 'tall.jpg', label: 'Tall screenshot', src: 'https://picsum.photos/seed/superone-tall/800/1600', mimeType: 'image/jpeg' } },
  { label: 'Image · generated by tool (info button)', state: { kind: 'image', path: '/Users/me/proj/media/astronaut.png', name: 'astronaut.png', src: 'https://picsum.photos/seed/superone-tall/800/1600', mimeType: 'image/png', generation: TOOL_GENERATION } },
  { label: 'Image · generated, long prompt (scrolls)', state: { kind: 'image', path: '/Users/me/proj/media/astronaut-long.png', name: 'astronaut-long.png', src: 'https://picsum.photos/seed/superone-tall/800/1600', mimeType: 'image/png', generation: { ...TOOL_GENERATION, revisedPrompt: Array.from({ length: 14 }, () => TOOL_GENERATION.revisedPrompt).join(' ') } } },
  { label: 'Image · generated by Codex (info button)', state: { kind: 'image', path: '/Users/me/proj/media/codex.png', name: 'codex.png', src: 'https://picsum.photos/seed/superone-tall/800/1600', mimeType: 'image/png', generation: CODEX_GENERATION } },
  { label: 'Image · broken', state: { kind: 'image', name: 'broken.png', src: 'data:image/png;base64,AAAA', mimeType: 'image/png' } },
  { label: 'Video · downloaded', state: { kind: 'video', path: '/workspace/super-one/out/clip.mp4', name: 'clip.mp4', localUri: SAMPLE_CLIP_URI, mimeType: 'video/mp4', size: 31_813 } },
  { label: 'Video · undecodable', state: { kind: 'video', path: '/workspace/super-one/out/odd.mov', name: 'odd.mov', localUri: 'file:///cache/file-preview/missing.mov', mimeType: 'video/quicktime', size: 12 } },
  { label: 'Mermaid', state: { kind: 'mermaid', name: 'Mermaid', svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 80" width="240" height="80"><rect width="240" height="80" rx="10" fill="#1e1e2e"/><text x="120" y="48" text-anchor="middle" fill="#cdd6f4" font-size="16" font-family="system-ui">Start → End</text></svg>' } },
  { label: 'Code · cited line 16', state: { kind: 'text', path: PATH, name: 'PortableToolRow.tsx', text: CODE, size: CODE.length, markdown: false, line: 16 } },
  { label: 'Code · no anchor', state: { kind: 'text', path: PATH, name: 'PortableToolRow.tsx', text: CODE, size: CODE.length, markdown: false } },
  { label: 'Markdown', state: { kind: 'text', path: '/workspace/super-one/docs/preview.md', name: 'preview.md', text: MARKDOWN, size: MARKDOWN.length, markdown: true } },
  { label: 'Empty file', state: { kind: 'text', path: '/workspace/super-one/.gitkeep', name: '.gitkeep', text: '', size: 0, markdown: false } },
  { label: 'Loading', state: { kind: 'loading', path: PATH, name: 'PortableToolRow.tsx', line: 16 } },
  { label: 'Transfer · relay, awaiting confirm', state: { kind: 'transfer', ...HERO, needsConfirm: true, phase: 'idle' } },
  { label: 'Transfer · downloading', state: { kind: 'transfer', ...HERO, needsConfirm: true, phase: 'downloading', receivedBytes: 2_410_056 } },
  { label: 'Transfer · LAN, downloading', state: { kind: 'transfer', path: '/workspace/super-one/logs/dev.log', name: 'dev.log', size: 1_204_988, mimeType: 'application/octet-stream', needsConfirm: false, phase: 'downloading', receivedBytes: 402_000 } },
  { label: 'Transfer · ready to save', state: { kind: 'transfer', path: '/workspace/super-one/docs/spec.pdf', name: 'spec.pdf', size: 2_310_000, mimeType: 'application/pdf', needsConfirm: true, phase: 'ready', localUri: 'file:///cache/file-preview/spec.pdf' } },
  { label: 'Error', state: { kind: 'error', path: '/workspace/super-one/.env', name: '.env', message: 'path matches blacklist' } },
]
