import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#111111', paddingTop: 16, paddingHorizontal: 16 },
  flex: { flex: 1 },
  contentRow: { flex: 1, flexDirection: 'row' },
  mainPane: { flex: 1, minWidth: 0 },
  tabletSidebar: {
    width: 280, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: '#3f3f46',
    paddingRight: 14, marginRight: 14,
  },
  sidebarAction: { paddingVertical: 6 },
  top: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  back: { color: '#a78bfa', fontSize: 16 },
  title: { color: '#f4f4f5', fontSize: 24, fontWeight: '600', flex: 1 },
  input: {
    borderWidth: 1, borderColor: '#3f3f46', borderRadius: 8, color: '#f4f4f5',
    paddingHorizontal: 12, paddingVertical: 10, marginBottom: 10,
  },
  multi: { minHeight: 88, textAlignVertical: 'top' },
  btn: { backgroundColor: '#3f3f46', borderRadius: 8, paddingVertical: 12, alignItems: 'center', marginBottom: 12 },
  secondaryBtn: {
    borderWidth: 1, borderColor: '#3f3f46', borderRadius: 8, paddingVertical: 12,
    alignItems: 'center', marginBottom: 12,
  },
  btnText: { color: '#f4f4f5', fontWeight: '600' },
  code: { color: '#f4f4f5', fontSize: 32, letterSpacing: 8, textAlign: 'center', marginVertical: 16 },
  row: { paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#27272a' },
  rowTitle: { color: '#f4f4f5', fontSize: 16 },
  rowMeta: { color: '#71717a', fontSize: 12, marginTop: 4 },
  composer: { flexDirection: 'row', gap: 8, paddingVertical: 8, alignItems: 'center' },
  composerInput: {
    flex: 1, borderWidth: 1, borderColor: '#3f3f46', borderRadius: 8, color: '#f4f4f5',
    paddingHorizontal: 12, paddingVertical: 10, maxHeight: 120,
  },
  send: { backgroundColor: '#3f3f46', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 12 },
  attach: { backgroundColor: '#27272a', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12 },
  meta: { color: '#71717a', fontSize: 12, paddingVertical: 8 },
  modal: { flex: 1, backgroundColor: '#000000cc', justifyContent: 'center', padding: 24 },
  planBox: { maxHeight: 240, marginVertical: 12 },
  collabList: { maxHeight: 420, marginVertical: 12 },
  collabCard: { backgroundColor: '#18181b', borderRadius: 10, padding: 12, marginBottom: 8 },
  collabTask: { color: '#d4d4d8', fontSize: 13, marginTop: 8 },
  warningText: { color: '#fbbf24', fontSize: 12, marginTop: 6 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 8 },
  chip: { borderWidth: 1, borderColor: '#3f3f46', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  chipOn: { borderColor: '#a78bfa', backgroundColor: '#2a2140' },
  overlay: { maxHeight: 180, backgroundColor: '#18181b', borderRadius: 8, marginBottom: 8 },
  scannerBox: { height: 280, borderRadius: 12, overflow: 'hidden', marginBottom: 12 },
  scanner: { flex: 1 },
  scannerCancel: {
    position: 'absolute', right: 12, bottom: 12, backgroundColor: '#27272a',
    borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10,
  },
  attachmentStrip: { flexGrow: 0, marginBottom: 4 },
  attachmentStripContent: { gap: 6 },
  attachmentChip: {
    maxWidth: 180, borderWidth: 1, borderColor: '#3f3f46', backgroundColor: '#18181b',
    borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6,
  },
  attachmentText: { color: '#d4d4d8', fontSize: 12 },
  settingsContent: { gap: 12, paddingBottom: 24 },
  settingsCard: { backgroundColor: '#18181b', borderRadius: 12, padding: 14, gap: 10 },
  subCard: { backgroundColor: '#111111', borderRadius: 8, padding: 10, gap: 8 },
  selectedRow: { backgroundColor: '#2a2140', borderRadius: 8, paddingHorizontal: 10 },
  errorText: { color: '#f87171', fontSize: 12 },
  sectionTitle: { color: '#f4f4f5', fontSize: 17, fontWeight: '600' },
  modelStrip: { gap: 6 },
  rowBetween: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 6 },
  directoryText: { color: '#a1a1aa', flex: 1, fontSize: 13 },
  pathBar: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingBottom: 8 },
})
