export const SUPERONE_MCP_IPC_ENDPOINT_ENV = 'SUPERONE_MCP_IPC_ENDPOINT'
export const SUPERONE_MCP_IPC_TOKEN_ENV = 'SUPERONE_MCP_IPC_TOKEN'
export const SUPERONE_MCP_SESSION_ID_ENV = 'SUPERONE_MCP_SESSION_ID'
