export const SUPERONE_MCP_IPC_ENDPOINT_ENV = 'SUPERONE_MCP_IPC_ENDPOINT'
export const SUPERONE_MCP_IPC_TOKEN_ENV = 'SUPERONE_MCP_IPC_TOKEN'
export const SUPERONE_MCP_PROJECT_DIR_ENV = 'SUPERONE_MCP_PROJECT_DIR'
