import { Composition } from "remotion"
import {
  HelloWorld,
  HELLO_WORLD_DURATION_IN_FRAMES,
  HELLO_WORLD_FPS,
  HELLO_WORLD_HEIGHT,
  HELLO_WORLD_WIDTH,
  helloWorldDefaultProps,
  ChatStream,
  CHAT_STREAM_DURATION_IN_FRAMES,
  CHAT_STREAM_FPS,
  CHAT_STREAM_HEIGHT,
  CHAT_STREAM_WIDTH,
  chatStreamDefaultProps,
  NewSessionScene,
  NEW_SESSION_DURATION_IN_FRAMES,
  NEW_SESSION_FPS,
  NEW_SESSION_HEIGHT,
  NEW_SESSION_WIDTH,
  newSessionSceneDefaultProps,
  ToolBlockScene,
  TOOL_BLOCK_DURATION_IN_FRAMES,
  TOOL_BLOCK_FPS,
  TOOL_BLOCK_HEIGHT,
  TOOL_BLOCK_WIDTH,
  toolBlockSceneDefaultProps,
  PlanApprovalScene,
  PLAN_APPROVAL_DURATION_IN_FRAMES,
  PLAN_APPROVAL_FPS,
  PLAN_APPROVAL_HEIGHT,
  PLAN_APPROVAL_WIDTH,
  planApprovalSceneDefaultProps,
  ToolBlockGalleryScene,
  TOOL_GALLERY_DURATION_IN_FRAMES,
  TOOL_GALLERY_FPS,
  TOOL_GALLERY_HEIGHT,
  TOOL_GALLERY_WIDTH,
  toolBlockGallerySceneDefaultProps,
  MarkdownGalleryScene,
  MARKDOWN_GALLERY_DURATION_IN_FRAMES,
  MARKDOWN_GALLERY_FPS,
  MARKDOWN_GALLERY_HEIGHT,
  MARKDOWN_GALLERY_WIDTH,
  markdownGallerySceneDefaultProps,
  AskUserQuestionScene,
  ASK_USER_QUESTION_DURATION_IN_FRAMES,
  ASK_USER_QUESTION_FPS,
  ASK_USER_QUESTION_HEIGHT,
  ASK_USER_QUESTION_WIDTH,
  askUserQuestionSceneDefaultProps,
  PermissionGalleryScene,
  PERMISSION_GALLERY_DURATION_IN_FRAMES,
  PERMISSION_GALLERY_FPS,
  PERMISSION_GALLERY_HEIGHT,
  PERMISSION_GALLERY_WIDTH,
  permissionGallerySceneDefaultProps,
  FileTreeScene,
  FILE_TREE_DURATION_IN_FRAMES,
  FILE_TREE_FPS,
  FILE_TREE_HEIGHT,
  FILE_TREE_WIDTH,
  fileTreeSceneDefaultProps,
  FilePreviewScene,
  FILE_PREVIEW_DURATION_IN_FRAMES,
  FILE_PREVIEW_FPS,
  FILE_PREVIEW_HEIGHT,
  FILE_PREVIEW_WIDTH,
  filePreviewSceneDefaultProps,
  PopoverGalleryScene,
  POPOVER_GALLERY_DURATION_IN_FRAMES,
  POPOVER_GALLERY_FPS,
  POPOVER_GALLERY_HEIGHT,
  POPOVER_GALLERY_WIDTH,
  popoverGallerySceneDefaultProps,
  SlashCommandGalleryScene,
  SLASH_COMMAND_GALLERY_DURATION_IN_FRAMES,
  SLASH_COMMAND_GALLERY_FPS,
  SLASH_COMMAND_GALLERY_HEIGHT,
  SLASH_COMMAND_GALLERY_WIDTH,
  slashCommandGallerySceneDefaultProps,
  ChatInputGalleryScene,
  CHAT_INPUT_GALLERY_DURATION_IN_FRAMES,
  CHAT_INPUT_GALLERY_FPS,
  CHAT_INPUT_GALLERY_HEIGHT,
  CHAT_INPUT_GALLERY_WIDTH,
  chatInputGallerySceneDefaultProps,
  SubagentScene,
  SUBAGENT_DURATION_IN_FRAMES,
  SUBAGENT_FPS,
  SUBAGENT_HEIGHT,
  SUBAGENT_WIDTH,
  subagentSceneDefaultProps,
  SubagentGalleryScene,
  SUBAGENT_GALLERY_DURATION_IN_FRAMES,
  SUBAGENT_GALLERY_FPS,
  SUBAGENT_GALLERY_HEIGHT,
  SUBAGENT_GALLERY_WIDTH,
  subagentGallerySceneDefaultProps,
  ContextMenuGalleryScene,
  CONTEXT_MENU_GALLERY_DURATION_IN_FRAMES,
  CONTEXT_MENU_GALLERY_FPS,
  CONTEXT_MENU_GALLERY_HEIGHT,
  CONTEXT_MENU_GALLERY_WIDTH,
  contextMenuGallerySceneDefaultProps,
  ActivityPanelScene,
  ACTIVITY_PANEL_DURATION_IN_FRAMES,
  ACTIVITY_PANEL_FPS,
  ACTIVITY_PANEL_HEIGHT,
  ACTIVITY_PANEL_WIDTH,
  activityPanelSceneDefaultProps,
  MiniAppFullscreenScene,
  MINIAPP_FULLSCREEN_DURATION_IN_FRAMES,
  MINIAPP_FULLSCREEN_FPS,
  MINIAPP_FULLSCREEN_HEIGHT,
  MINIAPP_FULLSCREEN_WIDTH,
  miniAppFullscreenSceneDefaultProps,
  SidebarGalleryScene,
  SIDEBAR_GALLERY_DURATION_IN_FRAMES,
  SIDEBAR_GALLERY_FPS,
  SIDEBAR_GALLERY_HEIGHT,
  SIDEBAR_GALLERY_WIDTH,
  sidebarGallerySceneDefaultProps,
} from "@superone/video-compositions"

import "./index.css"

export const RemotionRoot = () => {
  return (
    <>
      <Composition
        id="HelloWorld"
        component={HelloWorld}
        durationInFrames={HELLO_WORLD_DURATION_IN_FRAMES}
        fps={HELLO_WORLD_FPS}
        width={HELLO_WORLD_WIDTH}
        height={HELLO_WORLD_HEIGHT}
        defaultProps={helloWorldDefaultProps}
      />
      <Composition
        id="ChatStream"
        component={ChatStream}
        durationInFrames={CHAT_STREAM_DURATION_IN_FRAMES}
        fps={CHAT_STREAM_FPS}
        width={CHAT_STREAM_WIDTH}
        height={CHAT_STREAM_HEIGHT}
        defaultProps={chatStreamDefaultProps}
      />
      <Composition
        id="NewSessionScene"
        component={NewSessionScene}
        durationInFrames={NEW_SESSION_DURATION_IN_FRAMES}
        fps={NEW_SESSION_FPS}
        width={NEW_SESSION_WIDTH}
        height={NEW_SESSION_HEIGHT}
        defaultProps={newSessionSceneDefaultProps}
      />
      <Composition
        id="ToolBlockScene"
        component={ToolBlockScene}
        durationInFrames={TOOL_BLOCK_DURATION_IN_FRAMES}
        fps={TOOL_BLOCK_FPS}
        width={TOOL_BLOCK_WIDTH}
        height={TOOL_BLOCK_HEIGHT}
        defaultProps={toolBlockSceneDefaultProps}
      />
      <Composition
        id="PlanApprovalScene"
        component={PlanApprovalScene}
        durationInFrames={PLAN_APPROVAL_DURATION_IN_FRAMES}
        fps={PLAN_APPROVAL_FPS}
        width={PLAN_APPROVAL_WIDTH}
        height={PLAN_APPROVAL_HEIGHT}
        defaultProps={planApprovalSceneDefaultProps}
      />
      <Composition
        id="ToolBlockGalleryScene"
        component={ToolBlockGalleryScene}
        durationInFrames={TOOL_GALLERY_DURATION_IN_FRAMES}
        fps={TOOL_GALLERY_FPS}
        width={TOOL_GALLERY_WIDTH}
        height={TOOL_GALLERY_HEIGHT}
        defaultProps={toolBlockGallerySceneDefaultProps}
      />
      <Composition
        id="MarkdownGalleryScene"
        component={MarkdownGalleryScene}
        durationInFrames={MARKDOWN_GALLERY_DURATION_IN_FRAMES}
        fps={MARKDOWN_GALLERY_FPS}
        width={MARKDOWN_GALLERY_WIDTH}
        height={MARKDOWN_GALLERY_HEIGHT}
        defaultProps={markdownGallerySceneDefaultProps}
      />
      <Composition
        id="AskUserQuestionScene"
        component={AskUserQuestionScene}
        durationInFrames={ASK_USER_QUESTION_DURATION_IN_FRAMES}
        fps={ASK_USER_QUESTION_FPS}
        width={ASK_USER_QUESTION_WIDTH}
        height={ASK_USER_QUESTION_HEIGHT}
        defaultProps={askUserQuestionSceneDefaultProps}
      />
      <Composition
        id="PermissionGalleryScene"
        component={PermissionGalleryScene}
        durationInFrames={PERMISSION_GALLERY_DURATION_IN_FRAMES}
        fps={PERMISSION_GALLERY_FPS}
        width={PERMISSION_GALLERY_WIDTH}
        height={PERMISSION_GALLERY_HEIGHT}
        defaultProps={permissionGallerySceneDefaultProps}
      />
      <Composition
        id="FileTreeScene"
        component={FileTreeScene}
        durationInFrames={FILE_TREE_DURATION_IN_FRAMES}
        fps={FILE_TREE_FPS}
        width={FILE_TREE_WIDTH}
        height={FILE_TREE_HEIGHT}
        defaultProps={fileTreeSceneDefaultProps}
      />
      <Composition
        id="FilePreviewScene"
        component={FilePreviewScene}
        durationInFrames={FILE_PREVIEW_DURATION_IN_FRAMES}
        fps={FILE_PREVIEW_FPS}
        width={FILE_PREVIEW_WIDTH}
        height={FILE_PREVIEW_HEIGHT}
        defaultProps={filePreviewSceneDefaultProps}
      />
      <Composition
        id="PopoverGalleryScene"
        component={PopoverGalleryScene}
        durationInFrames={POPOVER_GALLERY_DURATION_IN_FRAMES}
        fps={POPOVER_GALLERY_FPS}
        width={POPOVER_GALLERY_WIDTH}
        height={POPOVER_GALLERY_HEIGHT}
        defaultProps={popoverGallerySceneDefaultProps}
      />
      <Composition
        id="SlashCommandGalleryScene"
        component={SlashCommandGalleryScene}
        durationInFrames={SLASH_COMMAND_GALLERY_DURATION_IN_FRAMES}
        fps={SLASH_COMMAND_GALLERY_FPS}
        width={SLASH_COMMAND_GALLERY_WIDTH}
        height={SLASH_COMMAND_GALLERY_HEIGHT}
        defaultProps={slashCommandGallerySceneDefaultProps}
      />
      <Composition
        id="ChatInputGalleryScene"
        component={ChatInputGalleryScene}
        durationInFrames={CHAT_INPUT_GALLERY_DURATION_IN_FRAMES}
        fps={CHAT_INPUT_GALLERY_FPS}
        width={CHAT_INPUT_GALLERY_WIDTH}
        height={CHAT_INPUT_GALLERY_HEIGHT}
        defaultProps={chatInputGallerySceneDefaultProps}
      />
      <Composition
        id="SubagentScene"
        component={SubagentScene}
        durationInFrames={SUBAGENT_DURATION_IN_FRAMES}
        fps={SUBAGENT_FPS}
        width={SUBAGENT_WIDTH}
        height={SUBAGENT_HEIGHT}
        defaultProps={subagentSceneDefaultProps}
      />
      <Composition
        id="SubagentGalleryScene"
        component={SubagentGalleryScene}
        durationInFrames={SUBAGENT_GALLERY_DURATION_IN_FRAMES}
        fps={SUBAGENT_GALLERY_FPS}
        width={SUBAGENT_GALLERY_WIDTH}
        height={SUBAGENT_GALLERY_HEIGHT}
        defaultProps={subagentGallerySceneDefaultProps}
      />
      <Composition
        id="ContextMenuGalleryScene"
        component={ContextMenuGalleryScene}
        durationInFrames={CONTEXT_MENU_GALLERY_DURATION_IN_FRAMES}
        fps={CONTEXT_MENU_GALLERY_FPS}
        width={CONTEXT_MENU_GALLERY_WIDTH}
        height={CONTEXT_MENU_GALLERY_HEIGHT}
        defaultProps={contextMenuGallerySceneDefaultProps}
      />
      <Composition
        id="ActivityPanelScene"
        component={ActivityPanelScene}
        durationInFrames={ACTIVITY_PANEL_DURATION_IN_FRAMES}
        fps={ACTIVITY_PANEL_FPS}
        width={ACTIVITY_PANEL_WIDTH}
        height={ACTIVITY_PANEL_HEIGHT}
        defaultProps={activityPanelSceneDefaultProps}
      />
      <Composition
        id="SidebarGalleryScene"
        component={SidebarGalleryScene}
        durationInFrames={SIDEBAR_GALLERY_DURATION_IN_FRAMES}
        fps={SIDEBAR_GALLERY_FPS}
        width={SIDEBAR_GALLERY_WIDTH}
        height={SIDEBAR_GALLERY_HEIGHT}
        defaultProps={sidebarGallerySceneDefaultProps}
      />
      <Composition
        id="MiniAppFullscreenScene"
        component={MiniAppFullscreenScene}
        durationInFrames={MINIAPP_FULLSCREEN_DURATION_IN_FRAMES}
        fps={MINIAPP_FULLSCREEN_FPS}
        width={MINIAPP_FULLSCREEN_WIDTH}
        height={MINIAPP_FULLSCREEN_HEIGHT}
        defaultProps={miniAppFullscreenSceneDefaultProps}
      />
    </>
  )
}
