import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const chatHtml = await readFile(resolve(packageDir, 'dist/index.html'), 'utf8')
const terminalHtml = await readFile(resolve(packageDir, 'dist-terminal/terminal.html'), 'utf8')
const chatSource = [
  '/** Generated by `bun run build`; do not edit by hand. */',
  `export const CHAT_VIEW_HTML = ${JSON.stringify(chatHtml)}`,
  '',
].join('\n')
const terminalSource = [
  '/** Generated by `bun run build`; do not edit by hand. */',
  `export const TERMINAL_VIEW_HTML = ${JSON.stringify(terminalHtml)}`,
  '',
].join('\n')

await Promise.all([
  writeFile(resolve(packageDir, 'src/generated-host-html.ts'), chatSource),
  writeFile(resolve(packageDir, 'src/generated-terminal-html.ts'), terminalSource),
])
