import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const mobileDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const output = resolve(mobileDir, 'src/generated-model-viewer-html.ts')
type BundleBuilder = {
  onResolve(options: { filter: RegExp }, callback: (args: { path: string }) => { path: string; namespace: string }): void
  onLoad(options: { filter: RegExp; namespace: string }, callback: (args: { path: string }) => Promise<{ contents: string; loader: 'js' }>): void
}
const { Bun } = globalThis as typeof globalThis & {
  Bun: { build(options: object): Promise<{ success: boolean; outputs: Array<{ text(): Promise<string> }>; logs: unknown[] }> }
}
const build = await Bun.build({
  entrypoints: [resolve(mobileDir, 'model-viewer/entry.ts')],
  target: 'browser',
  minify: true,
  plugins: [{
    name: 'inline-draco-decoder',
    setup(builder: BundleBuilder) {
      builder.onResolve({ filter: /^three\/examples\/jsm\/libs\/draco\/gltf\/draco_(?:wasm_wrapper\.js|decoder\.wasm)\?url$/ },
        ({ path }) => ({ path: path.slice(0, -4), namespace: 'inline-draco' }))
      builder.onLoad({ filter: /./, namespace: 'inline-draco' }, async ({ path }) => {
        const mime = path.endsWith('.wasm') ? 'application/wasm' : 'text/javascript'
        const bytes = await readFile(fileURLToPath(import.meta.resolve(path)))
        return { contents: `export default ${JSON.stringify(`data:${mime};base64,${bytes.toString('base64')}`)}`, loader: 'js' }
      })
    },
  }],
})
if (!build.success || build.outputs.length !== 1) {
  throw new Error(`Could not bundle the offline model viewer: ${build.logs.join('\n')}`)
}
const script = await build.outputs[0].text()
const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta charset="utf-8"><style>html,body,#stage{width:100%;height:100%;margin:0;overflow:hidden;background:__MODEL_BACKGROUND__}canvas{display:block;touch-action:none}#status{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;padding:24px;text-align:center;color:__MODEL_FOREGROUND__;font:13px system-ui;pointer-events:none}#status:empty{display:none}#reset{position:absolute;top:12px;right:12px;border:0;border-radius:8px;padding:8px 11px;background:__MODEL_SURFACE__;color:__MODEL_FOREGROUND__;font:13px system-ui}</style></head><body><div id="stage"></div><div id="status">Loading model…</div><button id="reset" hidden>Reset view</button><script>window.modelPreviewTarget=__MODEL_TARGET__;</script><script type="module">${script.replace(/<\/script/gi, '<\\/script')}</script></body></html>`
await writeFile(output, `/** Generated by \`bun scripts/build-model-viewer.ts\`; do not edit. */\nexport const MODEL_VIEWER_HTML = ${JSON.stringify(html)}\n`)
