import { execFileSync } from 'node:child_process'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const mobileDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const output = resolve(mobileDir, 'src/generated-model-viewer-html.ts')
const buildDir = await mkdtemp(resolve(tmpdir(), 'superone-model-viewer-'))
let script: string
try {
  const bundlePath = resolve(buildDir, 'viewer.js')
  execFileSync('bun', ['build', resolve(mobileDir, 'model-viewer/entry.ts'), '--target=browser', '--minify', '--outfile', bundlePath], { stdio: 'pipe' })
  script = await readFile(bundlePath, 'utf8')
} finally {
  await rm(buildDir, { recursive: true, force: true })
}
const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta charset="utf-8"><style>html,body,#stage{width:100%;height:100%;margin:0;overflow:hidden;background:__MODEL_BACKGROUND__}canvas{display:block;touch-action:none}#status{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;padding:24px;text-align:center;color:__MODEL_FOREGROUND__;font:13px system-ui;pointer-events:none}#status:empty{display:none}#reset{position:absolute;top:12px;right:12px;border:0;border-radius:8px;padding:8px 11px;background:__MODEL_SURFACE__;color:__MODEL_FOREGROUND__;font:13px system-ui}</style></head><body><div id="stage"></div><div id="status">Loading model…</div><button id="reset" hidden>Reset view</button><script>window.modelPreviewTarget=__MODEL_TARGET__;</script><script>${script.replace(/<\/script/gi, '<\\/script')}</script></body></html>`
await writeFile(output, `/** Generated by \`bun scripts/build-model-viewer.ts\`; do not edit. */\nexport const MODEL_VIEWER_HTML = ${JSON.stringify(html)}\n`)
