import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import {
  HARNESS_DEFAULT_TOKENS,
  inkForFill,
  oklchToLinearSRGB,
  type LCH,
} from '../../../packages/shared/src/harness/harness-brand'
import type { HarnessId } from '../../../packages/shared/src/session-types'

const appRoot = resolve(import.meta.dirname, '..')
const themeCssPath = resolve(appRoot, '../../packages/ui/src/styles/theme.css')
const outputPath = resolve(appRoot, 'src/theme/tokens.generated.ts')
const css = readFileSync(themeCssPath, 'utf8')

type Palette = Record<string, string>

function srgbChannel(value: number): number {
  const clipped = Math.max(0, Math.min(1, value))
  return clipped <= 0.0031308
    ? 12.92 * clipped
    : 1.055 * clipped ** (1 / 2.4) - 0.055
}

function hex(lch: LCH): string {
  const channels = oklchToLinearSRGB(lch.l, lch.c, lch.h)
    .map(srgbChannel)
    .map((value) => Math.round(value * 255).toString(16).padStart(2, '0'))
  const alpha = lch.a < 1 ? Math.round(lch.a * 255).toString(16).padStart(2, '0') : ''
  return `#${channels.join('')}${alpha}`
}

function parseOklch(scope: string, token: string): LCH {
  const match = scope.match(new RegExp(`--${token}:\\s*oklch\\(([-.\\d]+)\\s+([-.\\d]+)\\s+([-.\\d]+)(?:\\s*\\/\\s*([-.\\d]+)%?)?\\)`))
  if (!match) throw new Error(`missing literal --${token} in desktop theme`)
  const rawAlpha = match[4] == null ? 1 : Number(match[4])
  return { l: Number(match[1]), c: Number(match[2]), h: Number(match[3]), a: rawAlpha > 1 ? rawAlpha / 100 : rawAlpha }
}

function scopeBody(selector: string): string {
  const start = css.indexOf(selector)
  if (start < 0) throw new Error(`missing ${selector} in desktop theme`)
  const open = css.indexOf('{', start)
  let depth = 0
  for (let index = open; index < css.length; index += 1) {
    if (css[index] === '{') depth += 1
    if (css[index] === '}') depth -= 1
    if (depth === 0) return css.slice(open + 1, index)
  }
  throw new Error(`unterminated ${selector} in desktop theme`)
}

const rootScope = scopeBody(':root,')
const darkScope = scopeBody('.dark {')
const statusTokens = ['success', 'warning', 'error'] as const

function lightPalette(harness: HarnessId): Palette {
  const tokens = HARNESS_DEFAULT_TOKENS[harness]
  const primary = tokens['--primary']
  return {
    background: hex(tokens['--background']),
    surface: hex(tokens['--card']),
    elevated: hex(tokens['--popover']),
    foreground: hex(tokens['--foreground']),
    mutedForeground: hex(tokens['--muted-foreground']),
    border: hex(tokens['--border']),
    input: hex(tokens['--input']),
    primary: hex(primary),
    primaryForeground: hex(inkForFill(primary)),
    secondary: hex(tokens['--secondary']),
    muted: hex(tokens['--muted']),
    success: hex(parseOklch(rootScope, 'success')),
    warning: hex(parseOklch(rootScope, 'warning')),
    error: hex(parseOklch(rootScope, 'error')),
    scrim: '#000000cc',
  }
}

function darkPalette(): Palette {
  const read = (token: string) => hex(parseOklch(darkScope, token))
  return {
    background: read('background'),
    surface: read('card'),
    elevated: read('popover'),
    foreground: read('foreground'),
    mutedForeground: read('muted-foreground'),
    border: read('border'),
    input: read('input'),
    primary: read('primary'),
    primaryForeground: read('primary-foreground'),
    secondary: read('secondary'),
    muted: read('muted'),
    ...Object.fromEntries(statusTokens.map((token) => [token, read(token)])),
    scrim: '#000000cc',
  }
}

const harnesses = Object.keys(HARNESS_DEFAULT_TOKENS) as HarnessId[]
const light = Object.fromEntries(harnesses.map((harness) => [harness, lightPalette(harness)]))
const output = `/* Generated by scripts/generate-theme-tokens.ts from desktop theme.css and harness-brand.ts. */
import type { HarnessId } from '@superone/shared/agent-types'

export type GeneratedThemeColors = {
${Object.keys(darkPalette()).map((key) => `  ${key}: string`).join('\n')}
}

export const GENERATED_DARK_COLORS: GeneratedThemeColors = ${JSON.stringify(darkPalette(), null, 2)}

export const GENERATED_LIGHT_COLORS: Record<HarnessId, GeneratedThemeColors> = ${JSON.stringify(light, null, 2)}
`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, output)
