import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/** Builds an offline viewer page that `CachedFileViewer` writes beside a cached file. */

export const mobileDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')

export type BundleBuilder = {
  onResolve(options: { filter: RegExp }, callback: (args: { path: string }) => { path: string; namespace: string }): void
  onLoad(options: { filter: RegExp; namespace: string }, callback: (args: { path: string }) => Promise<{ contents: string; loader: 'js' }>): void
}
type BundlePlugin = { name: string; setup(builder: BundleBuilder): void }
const { Bun } = globalThis as typeof globalThis & {
  Bun: { build(options: object): Promise<{ success: boolean; outputs: Array<{ text(): Promise<string> }>; logs: unknown[] }> }
}

/** `entry` bundled into the one module script the page inlines. */
export async function bundleViewerScript(entry: string, plugins: BundlePlugin[], label: string): Promise<string> {
  const build = await Bun.build({ entrypoints: [resolve(mobileDir, entry)], target: 'browser', minify: true, plugins })
  if (!build.success || build.outputs.length !== 1) {
    throw new Error(`Could not bundle the offline ${label} viewer: ${build.logs.join('\n')}`)
  }
  return build.outputs[0].text()
}

/** The page around the script: `__VIEWER_*__` placeholders are filled in on the phone. */
export async function writeViewerPage({ output, exportName, generator, viewport, style, body, script }: {
  output: string
  exportName: string
  generator: string
  viewport: string
  style: string
  body: string
  script: string
}): Promise<void> {
  const html = `<!doctype html><html><head><meta name="viewport" content="${viewport}"><meta charset="utf-8"><style>${style}</style></head><body>${body}<script>window.viewerTarget=__VIEWER_TARGET__;</script><script type="module">${script.replace(/<\/script/gi, '<\\/script')}</script></body></html>`
  await writeFile(resolve(mobileDir, output), `/** Generated by \`bun ${generator}\`; do not edit. */\nexport const ${exportName} = ${JSON.stringify(html)}\n`)
}
