import type { McpEntry, SkillEntry } from "./types"

export const SKILLS: SkillEntry[] = [
  {
    slug: "refactor-this",
    emoji: "🧹",
    hue: 220,
    name: { en: "Refactor This", zh: "重构这段" },
    tagline: {
      en: "Surgical refactors with a plan-first workflow.",
      zh: "先出方案再动刀的外科式重构。",
    },
    description: {
      en: "Selects a file or symbol, drafts a refactor plan, then applies edits in reviewable steps. Great for extracting components, renaming across a codebase, or splitting bloated modules.",
      zh: "选中一段文件或符号,先生成重构方案,然后按可审查的步骤落地。适合抽组件、跨代码库改名、拆解臃肿模块。",
    },
    category: "development",
    authorType: "official",
    authorName: "SuperOne",
    tags: ["refactor", "code-quality", "plan-mode"],
    examplePrompts: [
      {
        en: "Extract the auth logic in user-service.ts into its own module.",
        zh: "把 user-service.ts 里的鉴权逻辑抽到独立模块。",
      },
      {
        en: "Rename `fetchUser` to `loadUser` everywhere it's used.",
        zh: "把所有用到 `fetchUser` 的地方改名成 `loadUser`。",
      },
    ],
    featured: true,
  },
  {
    slug: "pr-reviewer",
    emoji: "🔍",
    hue: 280,
    name: { en: "PR Reviewer", zh: "PR 审查员" },
    tagline: {
      en: "Reads the diff like a senior engineer.",
      zh: "像资深工程师那样读 diff。",
    },
    description: {
      en: "Pulls the current branch diff, flags correctness bugs, security issues and style drift. Posts findings inline as suggested comments.",
      zh: "拉取当前分支的 diff,标出正确性 bug、安全问题和风格漂移,以建议性评论的形式贴回来。",
    },
    category: "development",
    authorType: "official",
    authorName: "SuperOne",
    tags: ["review", "git", "security"],
    examplePrompts: [
      { en: "Review the current branch against main.", zh: "对比 main 审一下当前分支。" },
      { en: "Focus on the auth changes only.", zh: "只看鉴权相关的改动。" },
    ],
    featured: true,
  },
  {
    slug: "test-generator",
    emoji: "🧪",
    hue: 150,
    name: { en: "Test Generator", zh: "测试生成器" },
    tagline: {
      en: "Vitest / Jest tests inferred from real call sites.",
      zh: "从真实调用点反推 Vitest / Jest 测试。",
    },
    description: {
      en: "Reads how a function is actually used, then generates realistic unit and integration tests with edge cases. Works with Vitest, Jest, and Playwright.",
      zh: "读懂一个函数实际是怎么被用的,然后生成贴近现实的单元和集成测试,带边界用例。支持 Vitest、Jest、Playwright。",
    },
    category: "development",
    authorType: "official",
    authorName: "SuperOne",
    tags: ["testing", "vitest", "jest"],
    examplePrompts: [
      { en: "Generate tests for lib/format-date.ts.", zh: "给 lib/format-date.ts 生成测试。" },
    ],
  },
  {
    slug: "changelog-writer",
    emoji: "📰",
    hue: 35,
    name: { en: "Changelog Writer", zh: "更新日志撰写" },
    tagline: {
      en: "Turns commits into release notes humans want to read.",
      zh: "把 commit 提炼成人会想读的发布说明。",
    },
    description: {
      en: "Reads git history since the last tag, groups changes by audience impact (not by commit type), drafts release notes with a hook and a short summary per item.",
      zh: "读取上一个 tag 之后的 git 历史,按对用户的影响分组(而不是按 commit type),为每条变更写一个钩子标题和短摘要。",
    },
    category: "writing",
    authorType: "official",
    authorName: "SuperOne",
    tags: ["changelog", "release", "git"],
    examplePrompts: [
      { en: "Draft release notes for v1.4.", zh: "给 v1.4 起一份发布说明。" },
    ],
  },
  {
    slug: "deep-research",
    emoji: "🔭",
    hue: 200,
    name: { en: "Deep Research", zh: "深度调研" },
    tagline: {
      en: "Multi-pass web research with cited synthesis.",
      zh: "多轮联网调研,带引用的综合输出。",
    },
    description: {
      en: "Spawns parallel sub-agents to crawl sources, then merges findings into a structured brief with citations. Great for competitive research and technical scouting.",
      zh: "并发派发子 agent 去爬资料,然后把发现汇成带引用的结构化简报。适合竞品研究、技术选型探路。",
    },
    category: "research",
    authorType: "official",
    authorName: "SuperOne",
    tags: ["research", "web", "citations"],
    examplePrompts: [
      {
        en: "Compare the top 5 vector databases as of 2026.",
        zh: "对比 2026 年最热门的 5 个向量数据库。",
      },
    ],
    featured: true,
  },
  {
    slug: "doc-site-builder",
    emoji: "📚",
    hue: 175,
    name: { en: "Doc Site Builder", zh: "文档站搭建" },
    tagline: {
      en: "Scaffold a docs site that matches your codebase.",
      zh: "按你代码库的样子搭一个文档站。",
    },
    description: {
      en: "Scans your repo, infers an information architecture, and scaffolds a Nextra / Starlight site with starter pages and a working sidebar.",
      zh: "扫一遍仓库,推断信息架构,然后用 Nextra / Starlight 生成一个带初始页面和侧边栏的文档站。",
    },
    category: "writing",
    authorType: "community",
    authorName: "@hangqiwu",
    tags: ["docs", "scaffold", "nextra"],
    examplePrompts: [
      { en: "Build me a docs site for this monorepo.", zh: "给这个 monorepo 搭一个文档站。" },
    ],
  },
  {
    slug: "sql-analyst",
    emoji: "📊",
    hue: 260,
    name: { en: "SQL Analyst", zh: "SQL 分析师" },
    tagline: {
      en: "Translate questions to SQL against your schema.",
      zh: "对着你的 schema 把问题翻译成 SQL。",
    },
    description: {
      en: "Introspects schema via the Postgres MCP, writes correct SQL, runs it, and explains the result with a chart suggestion.",
      zh: "通过 Postgres MCP 反射 schema,写出正确的 SQL,跑出来,并附上结果解读和图表建议。",
    },
    category: "data",
    authorType: "official",
    authorName: "SuperOne",
    tags: ["sql", "postgres", "analytics"],
    examplePrompts: [
      {
        en: "Show daily active users over the last 30 days.",
        zh: "看过去 30 天的每日活跃用户。",
      },
    ],
  },
  {
    slug: "migration-pilot",
    emoji: "🚚",
    hue: 25,
    name: { en: "Migration Pilot", zh: "迁移领航" },
    tagline: {
      en: "Step-by-step assistant for risky upgrades.",
      zh: "高风险升级的分步领航。",
    },
    description: {
      en: "Plans framework / library migrations (Next 15→16, React 18→19, Tailwind 3→4) — produces a checklist, runs codemods, then verifies builds at each step.",
      zh: "为框架/库迁移(Next 15→16、React 18→19、Tailwind 3→4)出 checklist,跑 codemod,每一步都验证构建。",
    },
    category: "development",
    authorType: "official",
    authorName: "SuperOne",
    tags: ["migration", "upgrade", "codemod"],
    examplePrompts: [
      { en: "Migrate this project to Tailwind 4.", zh: "把这个项目迁到 Tailwind 4。" },
    ],
  },
  {
    slug: "readme-polisher",
    emoji: "✨",
    hue: 320,
    name: { en: "README Polisher", zh: "README 抛光" },
    tagline: {
      en: "From bare scaffold to publish-ready README.",
      zh: "从光秃秃的脚手架到可以发布的 README。",
    },
    description: {
      en: "Reads your package.json, infers what the project does, and rewrites the README with install, usage, badges, and an honest features list.",
      zh: "读 package.json 推断项目做什么,然后重写 README:安装、用法、徽章和一份诚实的功能列表。",
    },
    category: "writing",
    authorType: "community",
    authorName: "@mira-codes",
    tags: ["readme", "docs", "open-source"],
    examplePrompts: [
      { en: "Polish the README for this package.", zh: "给这个包抛光一下 README。" },
    ],
  },
  {
    slug: "spec-to-code",
    emoji: "📐",
    hue: 240,
    name: { en: "Spec → Code", zh: "规格 → 代码" },
    tagline: {
      en: "Paste a spec, get a working PR.",
      zh: "贴一份规格,拿回一个能跑的 PR。",
    },
    description: {
      en: "Reads a markdown or OpenAPI spec, drafts an implementation plan, asks for approval, then implements with tests on a fresh branch.",
      zh: "读 markdown 或 OpenAPI 规格,生成实现计划,等你确认后在新分支上带测试落地。",
    },
    category: "development",
    authorType: "official",
    authorName: "SuperOne",
    tags: ["spec", "openapi", "plan-mode"],
    examplePrompts: [
      {
        en: "Implement this OpenAPI spec against the existing handler.",
        zh: "对着现有 handler 实现这份 OpenAPI 规格。",
      },
    ],
  },
  {
    slug: "daily-standup",
    emoji: "☕",
    hue: 50,
    name: { en: "Daily Standup", zh: "每日站会" },
    tagline: {
      en: "Stand-up notes pulled from your actual day.",
      zh: "从你真实的一天里拉出来的站会笔记。",
    },
    description: {
      en: "Aggregates yesterday's commits, closed Linear tickets and Slack threads into a standup-ready summary you can paste in.",
      zh: "把昨天的 commit、已关闭的 Linear 工单和 Slack 讨论聚合成可以直接贴的站会摘要。",
    },
    category: "productivity",
    authorType: "community",
    authorName: "@toomas",
    tags: ["standup", "linear", "slack"],
    examplePrompts: [
      { en: "Write my standup for today.", zh: "帮我写今天的站会。" },
    ],
  },
  {
    slug: "linear-triager",
    emoji: "🎯",
    hue: 290,
    name: { en: "Linear Triager", zh: "Linear 分诊" },
    tagline: {
      en: "Auto-label and route the inbox.",
      zh: "自动给收件箱打标签和分流。",
    },
    description: {
      en: "Reads inbox issues, labels them, assigns owners using team config, and posts a triage digest. Runs as a recurring routine.",
      zh: "读收件箱里的 issue,自动打标签,按团队配置分配负责人,再发一份分诊摘要。可以做成定时任务。",
    },
    category: "productivity",
    authorType: "community",
    authorName: "@halfwidth",
    tags: ["linear", "triage", "automation"],
    examplePrompts: [
      { en: "Triage the Linear inbox now.", zh: "现在分诊一下 Linear 收件箱。" },
    ],
  },
  {
    slug: "blog-from-commits",
    emoji: "✍️",
    hue: 10,
    name: { en: "Blog from Commits", zh: "Commit 写博客" },
    tagline: {
      en: "Engineering blog posts from your git log.",
      zh: "从 git log 写一篇工程博客。",
    },
    description: {
      en: "Picks a window of commits, finds the narrative thread, and drafts a long-form post with code excerpts and diagrams.",
      zh: "选一段时间窗的 commit,提炼故事线,写一篇带代码片段和图解的长文。",
    },
    category: "writing",
    authorType: "community",
    authorName: "@dustpan",
    tags: ["blog", "writing", "git"],
    examplePrompts: [
      {
        en: "Write a blog post about the changes shipped last sprint.",
        zh: "为上个 sprint 上线的改动写一篇博客。",
      },
    ],
  },
  {
    slug: "flashcard-coach",
    emoji: "🎴",
    hue: 330,
    name: { en: "Flashcard Coach", zh: "卡片教练" },
    tagline: {
      en: "Spaced-repetition decks from any source material.",
      zh: "从任意学习材料生成间隔重复卡组。",
    },
    description: {
      en: "Reads PDFs, notes, or web pages and produces an Anki-ready deck with cloze cards and quality tags.",
      zh: "读 PDF、笔记或网页,产出 Anki 可导入的卡组,带挖空和质量标签。",
    },
    category: "creative",
    authorType: "community",
    authorName: "@aoife",
    tags: ["anki", "learning", "pdf"],
    examplePrompts: [
      {
        en: "Turn this paper into an Anki deck about transformer scaling.",
        zh: "把这篇论文做成一份关于 transformer 扩展性的 Anki 卡组。",
      },
    ],
  },
]

export const MCPS: McpEntry[] = [
  {
    slug: "github",
    emoji: "🐙",
    hue: 250,
    name: { en: "GitHub", zh: "GitHub" },
    vendor: "Anthropic",
    tagline: {
      en: "Issues, PRs, files and code search.",
      zh: "Issue、PR、文件和代码搜索。",
    },
    description: {
      en: "Read and write GitHub issues / PRs, search code, manage labels, and review pull requests. Authenticates via a personal access token.",
      zh: "读写 GitHub issue / PR,搜索代码,管理标签,审查 PR。通过 personal access token 鉴权。",
    },
    category: "devtools",
    authorType: "official",
    transport: "stdio",
    authRequired: true,
    capabilities: { tools: 18, resources: 4, prompts: 2 },
    highlightedTools: ["create_issue", "search_code", "merge_pr", "list_commits"],
    tags: ["git", "github", "pr"],
    featured: true,
  },
  {
    slug: "filesystem",
    emoji: "📁",
    hue: 30,
    name: { en: "Filesystem", zh: "本地文件系统" },
    vendor: "Anthropic",
    tagline: {
      en: "Sandboxed file access for the agent.",
      zh: "给 agent 的沙箱化文件访问。",
    },
    description: {
      en: "Expose a folder to the agent with read / write / search tools. Path-scoped so the agent can't escape the directory you choose.",
      zh: "把一个目录暴露给 agent,带读 / 写 / 搜索工具。路径限定,agent 跳不出你指定的目录。",
    },
    category: "devtools",
    authorType: "official",
    transport: "stdio",
    authRequired: false,
    capabilities: { tools: 8, resources: 0, prompts: 0 },
    highlightedTools: ["read_file", "write_file", "search", "list_dir"],
    tags: ["files", "sandbox", "local"],
  },
  {
    slug: "postgres",
    emoji: "🐘",
    hue: 215,
    name: { en: "Postgres", zh: "Postgres" },
    vendor: "Anthropic",
    tagline: {
      en: "Query Postgres with schema introspection.",
      zh: "带 schema 反射的 Postgres 查询。",
    },
    description: {
      en: "Run read-only or read-write SQL against a Postgres database. Auto-introspects schema and exposes it as resources so the agent can plan queries.",
      zh: "对 Postgres 跑只读或读写 SQL。自动反射 schema 并作为资源暴露,让 agent 能规划查询。",
    },
    category: "storage",
    authorType: "official",
    transport: "stdio",
    authRequired: true,
    capabilities: { tools: 4, resources: 12, prompts: 1 },
    highlightedTools: ["query", "explain", "describe_table"],
    tags: ["sql", "postgres", "database"],
    featured: true,
  },
  {
    slug: "slack",
    emoji: "💬",
    hue: 300,
    name: { en: "Slack", zh: "Slack" },
    vendor: "@modelcontextprotocol",
    tagline: {
      en: "Read channels, post messages, search history.",
      zh: "读频道、发消息、搜历史。",
    },
    description: {
      en: "Post into channels, read recent threads, search across history. Useful for standups, on-call digests, and incident comms.",
      zh: "向频道发消息,读最近线程,搜历史记录。适合做站会、值班摘要、事故沟通。",
    },
    category: "communication",
    authorType: "community",
    transport: "stdio",
    authRequired: true,
    capabilities: { tools: 9, resources: 6, prompts: 0 },
    highlightedTools: ["post_message", "search_messages", "list_channels"],
    tags: ["slack", "chat", "team"],
  },
  {
    slug: "linear",
    emoji: "📋",
    hue: 270,
    name: { en: "Linear", zh: "Linear" },
    vendor: "@modelcontextprotocol",
    tagline: {
      en: "Issue tracking with project context.",
      zh: "带项目上下文的工单追踪。",
    },
    description: {
      en: "Read and write Linear issues, move tickets across states, add comments, and search by team / cycle / project.",
      zh: "读写 Linear 工单、推进状态、加评论,按团队 / cycle / 项目搜索。",
    },
    category: "productivity",
    authorType: "community",
    transport: "http",
    authRequired: true,
    capabilities: { tools: 11, resources: 4, prompts: 1 },
    highlightedTools: ["create_issue", "update_state", "search_issues"],
    tags: ["linear", "tasks", "tracking"],
    featured: true,
  },
  {
    slug: "notion",
    emoji: "🗒️",
    hue: 0,
    name: { en: "Notion", zh: "Notion" },
    vendor: "@modelcontextprotocol",
    tagline: {
      en: "Pages, databases, and block-level edits.",
      zh: "页面、数据库,block 级编辑。",
    },
    description: {
      en: "Read pages and databases, append blocks, run queries against database views. Great for living docs and knowledge bases.",
      zh: "读页面和数据库,追加 block,对数据库视图跑查询。适合活文档和知识库。",
    },
    category: "productivity",
    authorType: "community",
    transport: "http",
    authRequired: true,
    capabilities: { tools: 13, resources: 8, prompts: 0 },
    highlightedTools: ["append_block", "query_database", "search_pages"],
    tags: ["notion", "docs", "knowledge"],
  },
  {
    slug: "google-drive",
    emoji: "🗂️",
    hue: 130,
    name: { en: "Google Drive", zh: "Google Drive" },
    vendor: "Anthropic",
    tagline: {
      en: "Search and read across your Drive.",
      zh: "在你的 Drive 里搜索和阅读。",
    },
    description: {
      en: "OAuth-backed read access to Drive — search files, fetch contents, list folders. Handy when the canonical doc lives outside your repo.",
      zh: "基于 OAuth 的 Drive 只读访问 —— 搜文件、读内容、列文件夹。当权威文档在仓库之外时很有用。",
    },
    category: "productivity",
    authorType: "official",
    transport: "http",
    authRequired: true,
    capabilities: { tools: 5, resources: 0, prompts: 0 },
    highlightedTools: ["search_files", "read_file", "list_folder"],
    tags: ["google", "drive", "docs"],
  },
  {
    slug: "cloudflare",
    emoji: "☁️",
    hue: 25,
    name: { en: "Cloudflare", zh: "Cloudflare" },
    vendor: "Cloudflare",
    tagline: {
      en: "Workers, R2, DNS and KV — from the chat.",
      zh: "在对话里管 Workers、R2、DNS、KV。",
    },
    description: {
      en: "Manage Workers deploys, R2 buckets, DNS records, KV namespaces. Auth via Cloudflare API token scoped to specific accounts.",
      zh: "管理 Workers 发布、R2 桶、DNS 记录、KV 命名空间。通过限定账号的 Cloudflare API token 鉴权。",
    },
    category: "cloud",
    authorType: "official",
    transport: "http",
    authRequired: true,
    capabilities: { tools: 22, resources: 5, prompts: 3 },
    highlightedTools: ["deploy_worker", "put_r2_object", "create_dns_record"],
    tags: ["cloudflare", "workers", "r2"],
  },
  {
    slug: "stripe",
    emoji: "💳",
    hue: 240,
    name: { en: "Stripe", zh: "Stripe" },
    vendor: "Stripe",
    tagline: {
      en: "Customers, subscriptions, and invoices.",
      zh: "客户、订阅、发票。",
    },
    description: {
      en: "Inspect customers, subscriptions, invoices, and disputes. Read-only by default — write tools live behind an explicit allow-list.",
      zh: "查看客户、订阅、发票、争议。默认只读,写操作需要显式允许清单。",
    },
    category: "cloud",
    authorType: "official",
    transport: "http",
    authRequired: true,
    capabilities: { tools: 15, resources: 6, prompts: 0 },
    highlightedTools: ["get_customer", "list_invoices", "refund_charge"],
    tags: ["stripe", "billing", "payments"],
  },
  {
    slug: "brave-search",
    emoji: "🦁",
    hue: 20,
    name: { en: "Brave Search", zh: "Brave 搜索" },
    vendor: "@modelcontextprotocol",
    tagline: {
      en: "Web search without the SEO sludge.",
      zh: "没那么多 SEO 垃圾的网页搜索。",
    },
    description: {
      en: "Independent web index with a privacy-respecting API. Good fallback for research skills that need fresh sources.",
      zh: "独立网页索引,API 注重隐私。研究类 skill 需要新鲜信息源时是不错的补充。",
    },
    category: "search",
    authorType: "community",
    transport: "stdio",
    authRequired: true,
    capabilities: { tools: 2, resources: 0, prompts: 0 },
    highlightedTools: ["web_search", "news_search"],
    tags: ["search", "web", "brave"],
  },
  {
    slug: "puppeteer",
    emoji: "🎭",
    hue: 195,
    name: { en: "Puppeteer", zh: "Puppeteer" },
    vendor: "Anthropic",
    tagline: {
      en: "Headless browser the agent can drive.",
      zh: "agent 能操控的无头浏览器。",
    },
    description: {
      en: "Spin up a Chromium instance, navigate, click, screenshot, evaluate JS. Use for scraping, visual regression, and end-to-end checks.",
      zh: "启动 Chromium,导航、点击、截图、执行 JS。适合抓页、视觉回归、端到端校验。",
    },
    category: "search",
    authorType: "official",
    transport: "stdio",
    authRequired: false,
    capabilities: { tools: 12, resources: 0, prompts: 0 },
    highlightedTools: ["navigate", "click", "screenshot", "evaluate"],
    tags: ["browser", "scraping", "e2e"],
    featured: true,
  },
  {
    slug: "memory",
    emoji: "🧠",
    hue: 310,
    name: { en: "Memory", zh: "记忆" },
    vendor: "Anthropic",
    tagline: {
      en: "Persistent knowledge across conversations.",
      zh: "跨对话的持久知识。",
    },
    description: {
      en: "A simple knowledge graph the agent can write to and recall from. Keeps user preferences, project facts, and reusable references between sessions.",
      zh: "一个简单的知识图,agent 可以往里写、从里取。跨会话保留用户偏好、项目事实、可复用引用。",
    },
    category: "devtools",
    authorType: "official",
    transport: "stdio",
    authRequired: false,
    capabilities: { tools: 6, resources: 1, prompts: 0 },
    highlightedTools: ["remember", "recall", "forget"],
    tags: ["memory", "context", "persistence"],
  },
  {
    slug: "sqlite",
    emoji: "🗃️",
    hue: 165,
    name: { en: "SQLite", zh: "SQLite" },
    vendor: "@modelcontextprotocol",
    tagline: {
      en: "Local SQLite as a first-class data source.",
      zh: "把本地 SQLite 当成一等数据源。",
    },
    description: {
      en: "Point at a `.db` file and query it like Postgres. Schema is exposed as resources so the agent can write valid SQL on the first try.",
      zh: "指向一个 `.db` 文件,像 Postgres 一样查询。schema 作为资源暴露,agent 第一次就能写出合法 SQL。",
    },
    category: "storage",
    authorType: "community",
    transport: "stdio",
    authRequired: false,
    capabilities: { tools: 3, resources: 8, prompts: 0 },
    highlightedTools: ["query", "describe_schema"],
    tags: ["sqlite", "sql", "local"],
  },
  {
    slug: "sentry",
    emoji: "🛡️",
    hue: 350,
    name: { en: "Sentry", zh: "Sentry" },
    vendor: "@modelcontextprotocol",
    tagline: {
      en: "Triage production errors with the agent.",
      zh: "用 agent 分诊线上错误。",
    },
    description: {
      en: "Pull recent issues from Sentry, fetch stack traces, group by release, and link back to the offending commit. Great with the PR Reviewer skill.",
      zh: "从 Sentry 拉最近的 issue,取栈,按 release 分组,反查闯祸的 commit。和 PR Reviewer 配合很好。",
    },
    category: "cloud",
    authorType: "community",
    transport: "http",
    authRequired: true,
    capabilities: { tools: 7, resources: 3, prompts: 1 },
    highlightedTools: ["list_issues", "get_event", "resolve"],
    tags: ["sentry", "errors", "observability"],
  },
]

export function findSkill(slug: string): SkillEntry | undefined {
  return SKILLS.find((s) => s.slug === slug)
}

export function findMcp(slug: string): McpEntry | undefined {
  return MCPS.find((m) => m.slug === slug)
}
