import { StyleSheet } from 'react-native'
import type { MobileThemeTokens } from './tokens'

export function createMobileStyles({ colors, radius, spacing, type }: MobileThemeTokens) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background, paddingTop: spacing.lg, paddingHorizontal: spacing.lg },
    flex: { flex: 1 },
    contentRow: { flex: 1, flexDirection: 'row' },
    mainPane: { flex: 1, minWidth: 0 },
    tabletSidebar: {
      width: 280,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: colors.border,
      paddingRight: 14,
      marginRight: 14,
    },
    sidebarAction: { paddingVertical: 6 },
    top: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.md },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
    back: { color: colors.primary, fontSize: type.body },
    title: { color: colors.foreground, fontSize: type.display, fontWeight: '600', flex: 1 },
    input: {
      borderWidth: 1,
      borderColor: colors.input,
      borderRadius: radius.md,
      color: colors.foreground,
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
      marginBottom: 10,
    },
    multi: { minHeight: 88, textAlignVertical: 'top' },
    btn: {
      backgroundColor: colors.primary,
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      alignItems: 'center',
      marginBottom: spacing.md,
    },
    secondaryBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      alignItems: 'center',
      marginBottom: spacing.md,
    },
    btnText: { color: colors.primaryForeground, fontWeight: '600' },
    secondaryBtnText: { color: colors.foreground, fontWeight: '600' },
    code: { color: colors.foreground, fontSize: 32, letterSpacing: 8, textAlign: 'center', marginVertical: spacing.lg },
    row: { paddingVertical: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
    rowTitle: { color: colors.foreground, fontSize: type.body },
    rowMeta: { color: colors.mutedForeground, fontSize: type.meta, marginTop: spacing.xs },
    composer: { flexDirection: 'row', gap: spacing.sm, paddingVertical: spacing.sm, alignItems: 'center' },
    composerInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.input,
      borderRadius: radius.md,
      color: colors.foreground,
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
      maxHeight: 120,
    },
    send: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: 14, paddingVertical: spacing.md },
    attach: { backgroundColor: colors.secondary, borderRadius: radius.md, paddingHorizontal: spacing.md, paddingVertical: spacing.md },
    meta: { color: colors.mutedForeground, fontSize: type.meta, paddingVertical: spacing.sm },
    modal: { flex: 1, backgroundColor: colors.scrim, justifyContent: 'center', padding: spacing.xl },
    planBox: { maxHeight: 240, marginVertical: spacing.md },
    collabList: { maxHeight: 420, marginVertical: spacing.md },
    collabCard: { backgroundColor: colors.surface, borderRadius: 10, padding: spacing.md, marginBottom: spacing.sm },
    collabTask: { color: colors.foreground, fontSize: 13, marginTop: spacing.sm },
    warningText: { color: colors.warning, fontSize: type.meta, marginTop: 6 },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: spacing.sm },
    chip: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: spacing.xs },
    chipOn: { borderColor: colors.primary, backgroundColor: colors.muted },
    overlay: { maxHeight: 180, backgroundColor: colors.surface, borderRadius: radius.md, marginBottom: spacing.sm },
    scannerBox: { height: 280, borderRadius: radius.lg, overflow: 'hidden', marginBottom: spacing.md },
    scanner: { flex: 1 },
    scannerCancel: {
      position: 'absolute',
      right: spacing.md,
      bottom: spacing.md,
      backgroundColor: colors.secondary,
      borderRadius: radius.md,
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
    },
    screenSection: { flex: 1, gap: spacing.md },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl, gap: spacing.sm },
    emptyTitle: { color: colors.foreground, fontSize: type.body, fontWeight: '600' },
    emptyBody: { color: colors.mutedForeground, fontSize: 13, textAlign: 'center', lineHeight: 19 },
    iconBox: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.muted,
      borderRadius: 10,
    },
    devPairing: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, paddingTop: spacing.md },
    sessionCard: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: radius.lg,
      marginBottom: spacing.sm,
      padding: spacing.md,
      gap: spacing.sm,
    },
    sessionRecent: { borderColor: colors.primary },
    sessionMeta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
    attachmentStrip: { flexGrow: 0, marginBottom: spacing.xs },
    attachmentStripContent: { gap: 6 },
    attachmentChip: {
      maxWidth: 180,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: radius.pill,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    attachmentText: { color: colors.foreground, fontSize: type.meta },
    sharedFilePreview: { width: '100%', height: 260, borderRadius: radius.md, backgroundColor: colors.background },
    settingsContent: { gap: spacing.md, paddingBottom: spacing.xl },
    settingsCard: { backgroundColor: colors.surface, borderRadius: radius.lg, padding: 14, gap: 10 },
    subCard: { backgroundColor: colors.background, borderRadius: radius.md, padding: 10, gap: spacing.sm },
    selectedRow: { backgroundColor: colors.muted, borderRadius: radius.md, paddingHorizontal: 10 },
    errorText: { color: colors.error, fontSize: type.meta },
    sectionTitle: { color: colors.foreground, fontSize: type.title, fontWeight: '600' },
    modelStrip: { gap: 6 },
    rowBetween: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: 6 },
    directoryText: { color: colors.mutedForeground, flex: 1, fontSize: 13 },
    pathBar: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingBottom: spacing.sm },
  })
}

export type MobileStyles = ReturnType<typeof createMobileStyles>
