import { StyleSheet } from 'react-native'
import type { MobileThemeTokens } from './tokens'

export function createMobileStyles({ colors, radius, spacing, type }: MobileThemeTokens) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    flex: { flex: 1 },
    page: { flex: 1, paddingHorizontal: spacing.lg, paddingTop: spacing.md },
    contentRow: { flex: 1, flexDirection: 'row' },
    mainPane: { flex: 1, minWidth: 0 },
    tabletSidebar: {
      width: 280,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: colors.border,
      padding: spacing.md,
      backgroundColor: colors.surface,
    },
    sidebarAction: { paddingVertical: 6 },
    top: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, minHeight: 64, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: 0 },
    headerTitleGroup: { flex: 1, minWidth: 0, gap: spacing.xs },
    headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    headerMetaRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
    back: { color: colors.primary, fontSize: type.body },
    title: { color: colors.foreground, fontSize: type.title, fontWeight: '500', flexShrink: 1 },
    input: {
      borderWidth: 1,
      borderColor: colors.input,
      borderRadius: radius.md,
      color: colors.foreground,
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
      marginBottom: 10,
    },
    multi: { minHeight: 88, textAlignVertical: 'top' },
    btn: {
      backgroundColor: colors.primary,
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      alignItems: 'center',
      marginBottom: spacing.md,
    },
    secondaryBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      alignItems: 'center',
      marginBottom: spacing.md,
    },
    btnText: { color: colors.primaryForeground, fontWeight: '500', fontSize: 14 },
    secondaryBtnText: { color: colors.foreground, fontWeight: '500', fontSize: 14 },
    code: { color: colors.foreground, fontSize: 44, fontWeight: '600', letterSpacing: 10, textAlign: 'center', marginVertical: spacing.lg },
    row: { paddingVertical: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
    rowTitle: { color: colors.foreground, fontSize: type.body },
    rowMeta: { color: colors.mutedForeground, fontSize: type.meta, marginTop: spacing.xs },
    composer: { flexDirection: 'row', gap: spacing.sm, paddingVertical: spacing.sm, alignItems: 'center' },
    composerControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm },
    directoryHint: { color: colors.mutedForeground, flex: 1, fontSize: type.meta, textAlign: 'right' },
    queuedRow: { backgroundColor: colors.muted, borderRadius: radius.md, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
    todoPanel: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, paddingVertical: spacing.sm },
    todoHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
    todoList: { gap: spacing.xs, paddingLeft: spacing.xl, paddingTop: spacing.sm },
    todoRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
    composerInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.input,
      borderRadius: radius.md,
      color: colors.foreground,
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
      maxHeight: 120,
    },
    send: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: 14, paddingVertical: spacing.md },
    attach: { backgroundColor: colors.secondary, borderRadius: radius.md, paddingHorizontal: spacing.md, paddingVertical: spacing.md },
    meta: { color: colors.mutedForeground, fontSize: type.meta, paddingVertical: spacing.sm, paddingHorizontal: spacing.lg, backgroundColor: colors.surface },
    modal: { flex: 1, backgroundColor: colors.scrim, justifyContent: 'center', padding: spacing.xl },
    previewText: { color: colors.foreground, backgroundColor: colors.muted, borderRadius: radius.md, padding: spacing.md },
    warningText: { color: colors.warning, fontSize: type.meta, marginTop: 6 },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: spacing.sm },
    chip: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: spacing.xs },
    chipOn: { borderColor: colors.primary, backgroundColor: colors.muted },
    overlay: {
      maxHeight: 240,
      backgroundColor: colors.elevated,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      marginBottom: spacing.sm,
    },
    overlayHeader: {
      color: colors.mutedForeground,
      fontSize: type.meta,
      fontWeight: '600',
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
      paddingBottom: spacing.xs,
    },
    overlayRow: {
      alignItems: 'center',
      borderTopColor: colors.border,
      borderTopWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: spacing.sm,
      minHeight: 52,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    overlayIcon: {
      alignItems: 'center',
      backgroundColor: colors.muted,
      borderRadius: radius.sm,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    scannerBox: { flex: 1, borderRadius: radius.lg, overflow: 'hidden', marginBottom: spacing.md },
    scanner: { flex: 1 },
    scannerCancel: {
      position: 'absolute',
      right: spacing.md,
      bottom: spacing.md,
      backgroundColor: colors.secondary,
      borderRadius: radius.md,
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
    },
    screenSection: { flex: 1, gap: spacing.md },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl, gap: spacing.sm },
    emptyTitle: { color: colors.foreground, fontSize: type.body, fontWeight: '600' },
    emptyBody: { color: colors.mutedForeground, fontSize: 13, textAlign: 'center', lineHeight: 19 },
    iconBox: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.muted,
      borderRadius: 10,
    },
    devPairing: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, paddingTop: spacing.md },
    pairingActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    projectIndicators: { maxWidth: '48%', flexDirection: 'row', justifyContent: 'flex-end', flexWrap: 'wrap', gap: spacing.xs },
    sessionCard: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: radius.lg,
      padding: spacing.md,
      gap: spacing.sm,
    },
    sessionRecent: { backgroundColor: colors.surface },
    sessionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    sessionMeta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
    sessionSwitcherList: { maxHeight: 520 },
    attachmentStrip: { flexGrow: 0, marginBottom: spacing.xs },
    attachmentStripContent: { gap: 6 },
    attachmentChip: {
      maxWidth: 180,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: radius.pill,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    attachmentText: { color: colors.foreground, fontSize: type.meta },
    sharedFilePreview: { width: '100%', height: 260, borderRadius: radius.md, backgroundColor: colors.background },
    sharedFileHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
    sharedFileActions: { gap: spacing.sm },
    settingsContent: { gap: spacing.md, paddingBottom: spacing.xl },
    settingsCard: { backgroundColor: colors.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.lg, gap: spacing.md },
    subCard: { backgroundColor: colors.background, borderRadius: radius.md, padding: 10, gap: spacing.sm },
    selectedRow: { backgroundColor: colors.muted, borderRadius: radius.md, paddingHorizontal: 10 },
    errorText: { color: colors.error, fontSize: type.meta },
    sectionTitle: { color: colors.mutedForeground, fontSize: 13, fontWeight: '500' },
    modelStrip: { gap: 6 },
    rowBetween: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: 6 },
    directoryText: { color: colors.mutedForeground, flex: 1, fontSize: 13 },
    pathBar: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 48, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
    pathUp: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
    terminalToolbar: { flexGrow: 0, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border },
    terminalToolbarContent: { gap: spacing.xs, paddingVertical: spacing.sm },
    terminalKey: { minWidth: 46, alignItems: 'center', backgroundColor: colors.secondary, borderRadius: radius.sm, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm },
    disabledControl: { opacity: 0.4 },
  })
}

export type MobileStyles = ReturnType<typeof createMobileStyles>
