/* Generated by scripts/generate-theme-tokens.ts from desktop theme.css and harness-brand.ts. */

export type GeneratedThemeColors = {
  background: string
  surface: string
  elevated: string
  foreground: string
  mutedForeground: string
  border: string
  input: string
  primary: string
  primaryForeground: string
  secondary: string
  muted: string
  success: string
  warning: string
  error: string
  successForeground: string
  destructive: string
  destructiveForeground: string
  scrim: string
}

export const GENERATED_DARK_COLORS: GeneratedThemeColors = {
  "background": "#0a0a0a",
  "surface": "#171717",
  "elevated": "#171717",
  "foreground": "#fafafa",
  "mutedForeground": "#a1a1a1",
  "border": "#262626",
  "input": "#ffffff26",
  "primary": "#1570d1",
  "primaryForeground": "#fafafa",
  "secondary": "#262626",
  "muted": "#262626",
  "success": "#25984d",
  "warning": "#e7a13c",
  "error": "#ff6467",
  "successForeground": "#fcfcfc",
  "destructive": "#db423c",
  "destructiveForeground": "#fcfcfc",
  "scrim": "#000000cc"
}

/** Fixed for every harness — see `lightPalette` in the generator for why. */
export const GENERATED_LIGHT_COLORS: GeneratedThemeColors = {
  "background": "#f6f7f8",
  "surface": "#fcfefe",
  "elevated": "#fcfefe",
  "foreground": "#141619",
  "mutedForeground": "#5e6468",
  "border": "#d8dadc",
  "input": "#d8dadc",
  "primary": "#1379b0",
  "primaryForeground": "#fcfcfc",
  "secondary": "#dde0e2",
  "muted": "#dde0e2",
  "success": "#25984d",
  "successForeground": "#fcfcfc",
  "destructive": "#df0000",
  "destructiveForeground": "#fcfcfc",
  "warning": "#c37806",
  "error": "#d40c1a",
  "scrim": "#000000cc"
}
