/* Generated by scripts/generate-theme-tokens.ts from desktop theme.css and harness-brand.ts. */
import type { HarnessId } from '@superone/shared/agent-types'

export type GeneratedThemeColors = {
  background: string
  surface: string
  elevated: string
  foreground: string
  mutedForeground: string
  border: string
  input: string
  primary: string
  primaryForeground: string
  secondary: string
  muted: string
  success: string
  warning: string
  error: string
  scrim: string
}

export const GENERATED_DARK_COLORS: GeneratedThemeColors = {
  "background": "#0a0a0a",
  "surface": "#171717",
  "elevated": "#171717",
  "foreground": "#fafafa",
  "mutedForeground": "#a1a1a1",
  "border": "#262626",
  "input": "#ffffff26",
  "primary": "#1570d1",
  "primaryForeground": "#fafafa",
  "secondary": "#262626",
  "muted": "#262626",
  "success": "#25984d",
  "warning": "#e7a13c",
  "error": "#ff6467",
  "scrim": "#000000cc"
}

export const GENERATED_LIGHT_COLORS: Record<HarnessId, GeneratedThemeColors> = {
  "claude": {
    "background": "#f8f6f6",
    "surface": "#fefdfd",
    "elevated": "#fefdfd",
    "foreground": "#191514",
    "mutedForeground": "#69615f",
    "border": "#dcd9d8",
    "input": "#dcd9d8",
    "primary": "#bd4510",
    "primaryForeground": "#fcfcfc",
    "secondary": "#e2dfde",
    "muted": "#e2dfde",
    "success": "#25984d",
    "warning": "#c37806",
    "error": "#d40c1a",
    "scrim": "#000000cc"
  },
  "codex": {
    "background": "#f6f7f8",
    "surface": "#fcfefe",
    "elevated": "#fcfefe",
    "foreground": "#141619",
    "mutedForeground": "#5e6468",
    "border": "#d8dadc",
    "input": "#d8dadc",
    "primary": "#1379b0",
    "primaryForeground": "#fcfcfc",
    "secondary": "#dde0e2",
    "muted": "#dde0e2",
    "success": "#25984d",
    "warning": "#c37806",
    "error": "#d40c1a",
    "scrim": "#000000cc"
  },
  "acp": {
    "background": "#f6f7f8",
    "surface": "#fdfdfe",
    "elevated": "#fdfdfe",
    "foreground": "#151619",
    "mutedForeground": "#626369",
    "border": "#d9dadc",
    "input": "#d9dadc",
    "primary": "#604ef7",
    "primaryForeground": "#fcfcfc",
    "secondary": "#dfdfe2",
    "muted": "#dfdfe2",
    "success": "#25984d",
    "warning": "#c37806",
    "error": "#d40c1a",
    "scrim": "#000000cc"
  },
  "opencode": {
    "background": "#f6f7f6",
    "surface": "#fdfefd",
    "elevated": "#fdfefd",
    "foreground": "#141715",
    "mutedForeground": "#5f6560",
    "border": "#d9dbd9",
    "input": "#d9dbd9",
    "primary": "#158840",
    "primaryForeground": "#fcfcfc",
    "secondary": "#dee0de",
    "muted": "#dee0de",
    "success": "#25984d",
    "warning": "#c37806",
    "error": "#d40c1a",
    "scrim": "#000000cc"
  },
  "cursor": {
    "background": "#f5f7f7",
    "surface": "#fcfefe",
    "elevated": "#fcfefe",
    "foreground": "#131717",
    "mutedForeground": "#5d6566",
    "border": "#d8dbdb",
    "input": "#d8dbdb",
    "primary": "#14808f",
    "primaryForeground": "#fcfcfc",
    "secondary": "#dde0e1",
    "muted": "#dde0e1",
    "success": "#25984d",
    "warning": "#c37806",
    "error": "#d40c1a",
    "scrim": "#000000cc"
  },
  "dsh": {
    "background": "#f6f7f8",
    "surface": "#fdfdfe",
    "elevated": "#fdfdfe",
    "foreground": "#151619",
    "mutedForeground": "#606369",
    "border": "#d9dadc",
    "input": "#d9dadc",
    "primary": "#2b5ef8",
    "primaryForeground": "#fcfcfc",
    "secondary": "#dee0e2",
    "muted": "#dee0e2",
    "success": "#25984d",
    "warning": "#c37806",
    "error": "#d40c1a",
    "scrim": "#000000cc"
  }
}
