/**
 * systemd-user unit generation for superone.
 * First managed installation profile: systemd-user.
 */

export interface SystemdUnitOptions {
  /** Absolute path to the superone launcher/binary. */
  execStart: string
  /** Node data directory (SUPERONE_NODE_HOME). */
  nodeHome: string
  /** Explicit HOME for the service principal. */
  home: string
  /** Working directory (defaults to nodeHome). */
  workingDirectory?: string
  /** Bind host (default 127.0.0.1). */
  bindHost?: string
  /** Bind port (default 7788). */
  bindPort?: number
  /** Optional description. */
  description?: string
}

export function renderSystemdUserUnit(opts: SystemdUnitOptions): string {
  const workingDirectory = opts.workingDirectory ?? opts.nodeHome
  const bindHost = opts.bindHost ?? '127.0.0.1'
  const bindPort = opts.bindPort ?? 7788
  const description = opts.description ?? 'SuperOne CLI Service'

  return `# Generated by SuperOne — do not hand-edit unless you know the upgrade contract.
[Unit]
Description=${description}
After=default.target
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
WorkingDirectory=${workingDirectory}
Environment=HOME=${opts.home}
Environment=SUPERONE_NODE_HOME=${opts.nodeHome}
Environment=SUPERONE_NODE_HOST=${bindHost}
Environment=SUPERONE_NODE_PORT=${bindPort}
UMask=0077
ExecStart=${opts.execStart} start --foreground
Restart=on-failure
RestartSec=3
TimeoutStopSec=30
KillMode=control-group
# Resource caps are conservative defaults; operators may override via drop-ins.
MemoryMax=2G
TasksMax=4096

[Install]
WantedBy=default.target
`
}

export const SYSTEMD_USER_UNIT_NAME = 'superone.service'

export function systemdUserUnitPath(configHome?: string): string {
  const base = configHome || process.env.XDG_CONFIG_HOME || `${process.env.HOME || '~'}/.config`
  return `${base}/systemd/user/${SYSTEMD_USER_UNIT_NAME}`
}
