import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

type EventRow = { id: number; tag: string | null; data: string }
type Scenario = { recording: string; messageId: string; events: unknown[] }

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '../../..')
const recordingsDir = resolve(process.argv[2] ?? join(repoRoot, 'apps/desktop/scripts/recordings'))
const output = resolve(process.argv[3] ?? join(here, '../src/fixtures/recorded.generated.ts'))
const names = ['bg-agent-history', 'claude-todos', 'mermaid-latex', 'permission-flow', 'show-widget']
const scenarios: Scenario[] = []
const dropped: Array<{ recording: string; reason: string }> = []

function query<T>(database: string, sql: string): T[] {
  const result = Bun.spawnSync(['sqlite3', '-json', database, sql])
  if (!result.success) throw new Error(result.stderr.toString() || `sqlite3 exited ${result.exitCode}`)
  const output = result.stdout.toString().trim()
  return output ? JSON.parse(output) as T[] : []
}

function normalizeRecordedValue(value: unknown): unknown {
  if (typeof value === 'string') return value.replace(/[\t ]+$/gm, '')
  if (Array.isArray(value)) return value.map(normalizeRecordedValue)
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [key, normalizeRecordedValue(entry)]),
    )
  }
  return value
}

for (const name of names) {
  const path = join(recordingsDir, `${name}.db`)
  if (!existsSync(path)) {
    dropped.push({ recording: name, reason: 'recording database is missing' })
    continue
  }
  const hasEvents = query<{ count: number }>(path,
    "SELECT count(*) AS count FROM sqlite_master WHERE type='table' AND name='events'",
  )[0]?.count === 1
  if (!hasEvents) {
    dropped.push({ recording: name, reason: 'recording database has no events schema' })
    continue
  }
  const rows = query<EventRow>(path,
    "SELECT id, tag, data FROM events WHERE source='remote.out' AND tag IS NOT NULL AND tag <> '' ORDER BY id",
  )
  const byMessage = new Map<string, unknown[]>()
  for (const row of rows) {
    const events = byMessage.get(row.tag!) ?? []
    events.push(normalizeRecordedValue(JSON.parse(row.data)))
    byMessage.set(row.tag!, events)
  }
  for (const [messageId, events] of byMessage) scenarios.push({ recording: name, messageId, events })
  if (byMessage.size === 0) dropped.push({ recording: name, reason: 'remote.out has no tagged scenarios' })
}

const generated = `// Generated by ${basename(import.meta.path)}. Do not edit by hand.\n`
  + `import type { AgentEvent } from '@superone/shared/agent-types'\n\n`
  + `export type RecordedScenario = { recording: string; messageId: string; events: AgentEvent[] }\n\n`
  + `export const recordedScenarios = ${JSON.stringify(scenarios, null, 2)} as unknown as RecordedScenario[]\n\n`
  + `export const droppedRecordings = ${JSON.stringify(dropped, null, 2)} as const\n`

mkdirSync(dirname(output), { recursive: true })
writeFileSync(output, generated)
console.log(`exported ${scenarios.length} scenarios; dropped ${dropped.length}: ${output}`)
